language: javascript
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before_script:
  - npm install n
  - sudo npm install -g grunt

script: grunt test --verbose --force
