sudo: true
language: javascript
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before_install:
  - npm intall -g grunt-cli
  - npm install grunt-contrib-qunit
install:
  - npm install
before_script:

script: grunt test --verbose --force
